version: "3.9"

services:
  db:
    image: mysql:8.0
    restart: always
    env_file: .env
    ports:
      - "3307:3306"  # map to host port 3307 to avoid local MySQL conflict
    volumes:
      - mysql_data:/var/lib/mysql

  web:
    build: .
    restart: always
    command: >
      sh -c "python manage.py migrate &&
             python3 manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file: .env
    depends_on:
      - db

volumes:
  mysql_data:
